//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4>
    {
    	
    			public virtual System.Guid Id { get; set; }
    	
    	public C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel() : base() { }
    	public C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel(DataService.Models.Entities.C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4 entity) : base(entity) { }
    
    }
}
