//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Company>
    {
    	
    			public virtual int CompanyId { get; set; }
    			public virtual string CompanyName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreatedAt { get; set; }
    			public virtual Nullable<System.DateTime> UpdateAt { get; set; }
    	
    	public CompanyViewModel() : base() { }
    	public CompanyViewModel(DataService.Models.Entities.Company entity) : base(entity) { }
    
    }
}
