//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Contract>
    {
    	
    			public virtual int ContractId { get; set; }
    			public virtual int CompanyId { get; set; }
    			public virtual string ContractName { get; set; }
    			public virtual Nullable<System.DateTime> StartDate { get; set; }
    			public virtual Nullable<System.DateTime> EndDate { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreatedAt { get; set; }
    			public virtual Nullable<System.DateTime> UpdateAt { get; set; }
    	
    	public ContractViewModel() : base() { }
    	public ContractViewModel(DataService.Models.Entities.Contract entity) : base(entity) { }
    
    }
}
