//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Device>
    {
    	
    			public virtual int DeviceId { get; set; }
    			public virtual int AgencyId { get; set; }
    			public virtual int DeviceTypeId { get; set; }
    			public virtual string DeviceName { get; set; }
    			public virtual string DeviceCode { get; set; }
    			public virtual Nullable<System.DateTime> GuarantyStartDate { get; set; }
    			public virtual Nullable<System.DateTime> GuarantyEndDate { get; set; }
    			public virtual string Ip { get; set; }
    			public virtual string Port { get; set; }
    			public virtual string DeviceAccount { get; set; }
    			public virtual string DevicePassword { get; set; }
    			public virtual Nullable<System.DateTime> SettingDate { get; set; }
    			public virtual string Other { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual System.DateTime CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    	
    	public DeviceViewModel() : base() { }
    	public DeviceViewModel(DataService.Models.Entities.Device entity) : base(entity) { }
    
    }
}
