//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipCardViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.MembershipCard>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> CustomerId { get; set; }
    			public virtual string CSV { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> Status { get; set; }
    			public virtual Nullable<int> C_Level { get; set; }
    			public virtual Nullable<int> MembershipTypeId { get; set; }
    			public virtual Nullable<bool> IsSample { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual string ProductCode { get; set; }
    			public virtual Nullable<double> InitialValue { get; set; }
    			public virtual string MembershipCardCode { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual string CreateBy { get; set; }
    	
    	public MembershipCardViewModel() : base() { }
    	public MembershipCardViewModel(DataService.Models.Entities.MembershipCard entity) : base(entity) { }
    
    }
}
