//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Problem>
    {
    	
    			public virtual int ProblemId { get; set; }
    			public virtual int AgencyId { get; set; }
    			public virtual int ProblemStatus { get; set; }
    			public virtual string ProblemtName { get; set; }
    			public virtual Nullable<System.DateTime> StartDate { get; set; }
    			public virtual Nullable<System.DateTime> EndDate { get; set; }
    			public virtual string Feedback { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    	
    	public ProblemViewModel() : base() { }
    	public ProblemViewModel(DataService.Models.Entities.Problem entity) : base(entity) { }
    
    }
}
