//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.RequestHistory>
    {
    	
    			public virtual int RequestHistoryId { get; set; }
    			public virtual int RequestId { get; set; }
    			public virtual Nullable<int> Pre_It_SupporterId { get; set; }
    			public virtual Nullable<int> Pre_Status { get; set; }
    			public virtual Nullable<bool> IsITSupportAccept { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<System.DateTime> StartTime { get; set; }
    			public virtual Nullable<System.DateTime> EndTime { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual System.DateTime CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    	
    	public RequestHistoryViewModel() : base() { }
    	public RequestHistoryViewModel(DataService.Models.Entities.RequestHistory entity) : base(entity) { }
    
    }
}
