//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCategoryViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.RequestCategory>
    {
    	
    			public virtual int RequestCategoryId { get; set; }
    			public virtual string RequestCategoryName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual bool IsDelete { get; set; }
    			public virtual System.DateTime CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    	
    	public RequestCategoryViewModel() : base() { }
    	public RequestCategoryViewModel(DataService.Models.Entities.RequestCategory entity) : base(entity) { }
    
    }
}
