//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItemViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ServiceItem>
    {
    	
    			public virtual int ServiceItemId { get; set; }
    			public virtual Nullable<int> ServiceITSupportId { get; set; }
    			public virtual string ServiceItemName { get; set; }
    			public virtual Nullable<double> Price { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<bool> IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreateDate { get; set; }
    			public virtual Nullable<System.DateTime> UpdateDate { get; set; }
    	
    	public ServiceItemViewModel() : base() { }
    	public ServiceItemViewModel(DataService.Models.Entities.ServiceItem entity) : base(entity) { }
    
    }
}
