//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceITSupportViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.ServiceITSupport>
    {
    	
    			public virtual int ServiceITSupportId { get; set; }
    			public virtual string ServiceName { get; set; }
    			public virtual string Description { get; set; }
    			public virtual Nullable<bool> IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreatedAt { get; set; }
    			public virtual Nullable<System.DateTime> UpdatedAt { get; set; }
    	
    	public ServiceITSupportViewModel() : base() { }
    	public ServiceITSupportViewModel(DataService.Models.Entities.ServiceITSupport entity) : base(entity) { }
    
    }
}
