//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillViewModel : DataService.ViewModels.BaseEntityViewModel<DataService.Models.Entities.Skill>
    {
    	
    			public virtual int SkillId { get; set; }
    			public virtual int ITSupportId { get; set; }
    			public virtual Nullable<int> ServiceItemId { get; set; }
    			public virtual Nullable<int> MonthExperience { get; set; }
    			public virtual Nullable<bool> IsDelete { get; set; }
    			public virtual Nullable<System.DateTime> CreatedAt { get; set; }
    			public virtual Nullable<System.DateTime> UpdatedAt { get; set; }
    	
    	public SkillViewModel() : base() { }
    	public SkillViewModel(DataService.Models.Entities.Skill entity) : base(entity) { }
    
    }
}
