//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject_ODTS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractService
    {
        public int ContractServiceId { get; set; }
        public int ContractId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Service Service { get; set; }
    }
}
