//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IAgencyService : DataService.BaseConnect.IBaseService<Agency, AgencyViewModel>
    {
    }
    
    public partial class AgencyService : DataService.BaseConnect.BaseService<Agency, AgencyViewModel>, IAgencyService
    {
         public AgencyService()
         {
         }
        public AgencyService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IAgencyRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
