//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IC__MigrationHistoryService : DataService.BaseConnect.IBaseService<C__MigrationHistory, C__MigrationHistoryViewModel>
    {
    }
    
    public partial class C__MigrationHistoryService : DataService.BaseConnect.BaseService<C__MigrationHistory, C__MigrationHistoryViewModel>, IC__MigrationHistoryService
    {
         public C__MigrationHistoryService()
         {
         }
        public C__MigrationHistoryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IC__MigrationHistoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
