//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service : DataService.BaseConnect.IBaseService<C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4, C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel>
    {
    }
    
    public partial class C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service : DataService.BaseConnect.BaseService<C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4, C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel>, IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service
    {
         public C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service()
         {
         }
        public C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository repository) : base(unitOfWork, repository)
        {
        }
    }
}
