//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IContractService : DataService.BaseConnect.IBaseService<Contract, ContractViewModel>
    {
    }
    
    public partial class ContractService : DataService.BaseConnect.BaseService<Contract, ContractViewModel>, IContractService
    {
         public ContractService()
         {
         }
        public ContractService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IContractRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
