//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IContractServiceITSupportService : DataService.BaseConnect.IBaseService<ContractServiceITSupport, ContractServiceITSupportViewModel>
    {
    }
    
    public partial class ContractServiceITSupportService : DataService.BaseConnect.BaseService<ContractServiceITSupport, ContractServiceITSupportViewModel>, IContractServiceITSupportService
    {
         public ContractServiceITSupportService()
         {
         }
        public ContractServiceITSupportService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IContractServiceITSupportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
