//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IGuidelineService : DataService.BaseConnect.IBaseService<Guideline, GuidelineViewModel>
    {
    }
    
    public partial class GuidelineService : DataService.BaseConnect.BaseService<Guideline, GuidelineViewModel>, IGuidelineService
    {
         public GuidelineService()
         {
         }
        public GuidelineService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IGuidelineRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
