//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IMembershipCardTypeService : DataService.BaseConnect.IBaseService<MembershipCardType, MembershipCardTypeViewModel>
    {
    }
    
    public partial class MembershipCardTypeService : DataService.BaseConnect.BaseService<MembershipCardType, MembershipCardTypeViewModel>, IMembershipCardTypeService
    {
         public MembershipCardTypeService()
         {
         }
        public MembershipCardTypeService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IMembershipCardTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
