//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IMembershipCardService : DataService.BaseConnect.IBaseService<MembershipCard, MembershipCardViewModel>
    {
    }
    
    public partial class MembershipCardService : DataService.BaseConnect.BaseService<MembershipCard, MembershipCardViewModel>, IMembershipCardService
    {
         public MembershipCardService()
         {
         }
        public MembershipCardService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IMembershipCardRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
