//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IProblemService : DataService.BaseConnect.IBaseService<Problem, ProblemViewModel>
    {
    }
    
    public partial class ProblemService : DataService.BaseConnect.BaseService<Problem, ProblemViewModel>, IProblemService
    {
         public ProblemService()
         {
         }
        public ProblemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IProblemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
