//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRatingProductService : DataService.BaseConnect.IBaseService<RatingProduct, RatingProductViewModel>
    {
    }
    
    public partial class RatingProductService : DataService.BaseConnect.BaseService<RatingProduct, RatingProductViewModel>, IRatingProductService
    {
         public RatingProductService()
         {
         }
        public RatingProductService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRatingProductRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
