//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IRequestTaskService : DataService.BaseConnect.IBaseService<RequestTask, RequestTaskViewModel>
    {
    }
    
    public partial class RequestTaskService : DataService.BaseConnect.BaseService<RequestTask, RequestTaskViewModel>, IRequestTaskService
    {
         public RequestTaskService()
         {
         }
        public RequestTaskService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IRequestTaskRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
