//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IServiceITSupportService : DataService.BaseConnect.IBaseService<ServiceITSupport, ServiceITSupportViewModel>
    {
    }
    
    public partial class ServiceITSupportService : DataService.BaseConnect.BaseService<ServiceITSupport, ServiceITSupportViewModel>, IServiceITSupportService
    {
         public ServiceITSupportService()
         {
         }
        public ServiceITSupportService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IServiceITSupportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
