//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface IServiceItemService : DataService.BaseConnect.IBaseService<ServiceItem, ServiceItemViewModel>
    {
    }
    
    public partial class ServiceItemService : DataService.BaseConnect.BaseService<ServiceItem, ServiceItemViewModel>, IServiceItemService
    {
         public ServiceItemService()
         {
         }
        public ServiceItemService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.IServiceItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
