//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ISkillService : DataService.BaseConnect.IBaseService<Skill, SkillViewModel>
    {
    }
    
    public partial class SkillService : DataService.BaseConnect.BaseService<Skill, SkillViewModel>, ISkillService
    {
         public SkillService()
         {
         }
        public SkillService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ISkillRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
