//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITicketHistoryService : DataService.BaseConnect.IBaseService<TicketHistory, TicketHistoryViewModel>
    {
    }
    
    public partial class TicketHistoryService : DataService.BaseConnect.BaseService<TicketHistory, TicketHistoryViewModel>, ITicketHistoryService
    {
         public TicketHistoryService()
         {
         }
        public TicketHistoryService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITicketHistoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
