//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITicketTaskService : DataService.BaseConnect.IBaseService<TicketTask, TicketTaskViewModel>
    {
    }
    
    public partial class TicketTaskService : DataService.BaseConnect.BaseService<TicketTask, TicketTaskViewModel>, ITicketTaskService
    {
         public TicketTaskService()
         {
         }
        public TicketTaskService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITicketTaskRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
