//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITicketService : DataService.BaseConnect.IBaseService<Ticket, TicketViewModel>
    {
    }
    
    public partial class TicketService : DataService.BaseConnect.BaseService<Ticket, TicketViewModel>, ITicketService
    {
         public TicketService()
         {
         }
        public TicketService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITicketRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
