//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    using DataService.ViewModels;
    
    public partial interface ITicketDetailService : DataService.BaseConnect.IBaseService<TicketDetail, TicketDetailViewModel>
    {
    }
    
    public partial class TicketDetailService : DataService.BaseConnect.BaseService<TicketDetail, TicketDetailViewModel>, ITicketDetailService
    {
         public TicketDetailService()
         {
         }
        public TicketDetailService(DataService.BaseConnect.IUnitOfWork unitOfWork, Repositories.ITicketDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
