//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int RequestHistoryId { get; set; }
        public int RequestId { get; set; }
        public Nullable<int> Pre_It_SupporterId { get; set; }
        public Nullable<int> Pre_Status { get; set; }
        public Nullable<bool> IsITSupportAccept { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ITSupporter ITSupporter { get; set; }
        public virtual Request Request { get; set; }
    }
}
