//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.DataAPIGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Api : DataService.DataAPIGen.BaseApi<DataService.Models.Entities.C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4, DataService.ViewModels.C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4ViewModel, DataService.Models.Entities.Services.IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Service>
    {
    	
    }
}
