//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository : DataService.BaseConnect.IBaseRepository<C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4>
    {
    }
    
    public partial class C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository : DataService.BaseConnect.BaseRepository<C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4>, IC_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository
    {
    	public C_TransactionIndex_2244ceaa_24f5_4fde_bd5f_baf8ea08cdc4Repository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    	{
    	}
    }
}
